# Generated by Django 5.2.5 on 2025-08-25 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorytransaction',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Inventory Transaction', 'verbose_name_plural': 'Inventory Transactions'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name': 'Purchase Order', 'verbose_name_plural': 'Purchase Orders'},
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'verbose_name': 'Sales Order', 'verbose_name_plural': 'Sales Orders'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='quantity_change',
            field=models.IntegerField(help_text='Positive for stock in, negative for stock out.'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='reason',
            field=models.CharField(blank=True, help_text='Reason for a manual adjustment.', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock_level',
            field=models.PositiveIntegerField(default=10, help_text='The stock level at which a reorder alert is triggered.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='The name of the product.', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='Unique Stock Keeping Unit (SKU) for the product.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Current number of units in stock.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='The selling price for one unit of the product.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='The cost per unit from the supplier.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='The selling price per unit at the time of sale.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_info',
            field=models.TextField(blank=True, help_text='Physical address or other contact details.'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(help_text='Contact email for the supplier.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(help_text='The name of the supplier company.', max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(help_text='Contact phone number for the supplier.', max_length=255),
        ),
    ]
